# Turkish Cities with codes
SEHIRLER = [
    {"kod": "ADA", "isim": "Adana"},
    {"kod": "ADI", "isim": "Adıyaman"},
    {"kod": "AFY", "isim": "Afyonkarahisar"},
    {"kod": "AGR", "isim": "Ağrı"},
    {"kod": "AKS", "isim": "Aksaray"},
    {"kod": "AMA", "isim": "Amasya"},
    {"kod": "ANK", "isim": "Ankara"},
    {"kod": "ANT", "isim": "Antalya"},
    {"kod": "ARD", "isim": "Ardahan"},
    {"kod": "ART", "isim": "Artvin"},
    {"kod": "AYD", "isim": "Aydın"},
    {"kod": "BAL", "isim": "Balıkesir"},
    {"kod": "BAR", "isim": "Bartın"},
    {"kod": "BAT", "isim": "Batman"},
    {"kod": "BAY", "isim": "Bayburt"},
    {"kod": "BIL", "isim": "Bilecik"},
    {"kod": "BIN", "isim": "Bingöl"},
    {"kod": "BIT", "isim": "Bitlis"},
    {"kod": "BOL", "isim": "Bolu"},
    {"kod": "BRD", "isim": "Burdur"},
    {"kod": "BRS", "isim": "Bursa"},
    {"kod": "CAN", "isim": "Çanakkale"},
    {"kod": "CKR", "isim": "Çankırı"},
    {"kod": "COR", "isim": "Çorum"},
    {"kod": "DEN", "isim": "Denizli"},
    {"kod": "DIY", "isim": "Diyarbakır"},
    {"kod": "DUZ", "isim": "Düzce"},
    {"kod": "EDI", "isim": "Edirne"},
    {"kod": "ELA", "isim": "Elazığ"},
    {"kod": "ERZ", "isim": "Erzincan"},
    {"kod": "EZR", "isim": "Erzurum"},
    {"kod": "ESK", "isim": "Eskişehir"},
    {"kod": "GAZ", "isim": "Gaziantep"},
    {"kod": "GIR", "isim": "Giresun"},
    {"kod": "GUM", "isim": "Gümüşhane"},
    {"kod": "HAK", "isim": "Hakkari"},
    {"kod": "HTY", "isim": "Hatay"},
    {"kod": "IGD", "isim": "Iğdır"},
    {"kod": "ISP", "isim": "Isparta"},
    {"kod": "IST", "isim": "İstanbul"},
    {"kod": "IZM", "isim": "İzmir"},
    {"kod": "KAH", "isim": "Kahramanmaraş"},
    {"kod": "KRB", "isim": "Karabük"},
    {"kod": "KRM", "isim": "Karaman"},
    {"kod": "KRS", "isim": "Kars"},
    {"kod": "KAS", "isim": "Kastamonu"},
    {"kod": "KAY", "isim": "Kayseri"},
    {"kod": "KLS", "isim": "Kilis"},
    {"kod": "KIR", "isim": "Kırıkkale"},
    {"kod": "KRK", "isim": "Kırklareli"},
    {"kod": "KRS", "isim": "Kırşehir"},
    {"kod": "KOC", "isim": "Kocaeli"},
    {"kod": "KON", "isim": "Konya"},
    {"kod": "KUT", "isim": "Kütahya"},
    {"kod": "MAL", "isim": "Malatya"},
    {"kod": "MAN", "isim": "Manisa"},
    {"kod": "MAR", "isim": "Mardin"},
    {"kod": "MER", "isim": "Mersin"},
    {"kod": "MUG", "isim": "Muğla"},
    {"kod": "MUS", "isim": "Muş"},
    {"kod": "NEV", "isim": "Nevşehir"},
    {"kod": "NIG", "isim": "Niğde"},
    {"kod": "ORD", "isim": "Ordu"},
    {"kod": "OSM", "isim": "Osmaniye"},
    {"kod": "RIZ", "isim": "Rize"},
    {"kod": "SAK", "isim": "Sakarya"},
    {"kod": "SAM", "isim": "Samsun"},
    {"kod": "SAN", "isim": "Şanlıurfa"},
    {"kod": "SII", "isim": "Siirt"},
    {"kod": "SIN", "isim": "Sinop"},
    {"kod": "SIR", "isim": "Şırnak"},
    {"kod": "SIV", "isim": "Sivas"},
    {"kod": "TEK", "isim": "Tekirdağ"},
    {"kod": "TOK", "isim": "Tokat"},
    {"kod": "TRA", "isim": "Trabzon"},
    {"kod": "TUN", "isim": "Tunceli"},
    {"kod": "USK", "isim": "Uşak"},
    {"kod": "VAN", "isim": "Van"},
    {"kod": "YAL", "isim": "Yalova"},
    {"kod": "YOZ", "isim": "Yozgat"},
    {"kod": "ZON", "isim": "Zonguldak"},
]

# Category and subcategory structure
KATEGORI_ALT_KATEGORI = {
    "Basınçlı Kaplar": [
        "Hidrofor",
        "Genleşme Tankı",
        "Hava Kompresörü",
        "Buhar Kazanı",
        "Sıcak Su Kazanı"
    ],
    "Asansör": [
        "Yolcu Asansörü",
        "Yük Asansörü",
        "Hasta Asansörü",
        "Panoramik Asansör"
    ],
    "Kaldırma Platformu": [
        "Engelli Platformu",
        "Yük Platformu",
        "Araç Lift",
        "Makaslı Platform"
    ],
    "Vinç": [
        "Köprü Vinç",
        "Portal Vinç",
        "Kule Vinç",
        "Mobil Vinç"
    ],
    "Forklift": [
        "Elektrikli Forklift",
        "Dizel Forklift",
        "LPG Forklift",
        "Reach Truck"
    ],
    "İskele": [
        "Sıva İskelesi",
        "Asma İskele",
        "Mobil İskele",
        "Çelik İskele"
    ]
}
